[build]
  publish = "build"
  command = "npm run build"

# SPA 라우팅을 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API 프록시 설정 (선택사항 - 백엔드가 CORS를 지원하지 않는 경우)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.com/api/:splat"
#   status = 200
#   force = true

# 환경별 배포 설정
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
