[build]
  publish = "build"
  command = "npm run build"

# SPA 라우팅을 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경별 배포 설정
[context.production.environment]
  NODE_ENV = "production"
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  REACT_APP_ENV = "production"
  REACT_APP_DISABLE_CONSOLE = "true"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
